# This is a basic workflow to help you get started with Actions

name: publish

strategy:
  matrix:
    node-version: [12.x]

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    environment: Publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build site
        run: |
            npm install
            npx @11ty/eleventy --config=eleventy-config.js --output=rehydrate
      # Runs a single command using the runners shell
      - name: s3cmd for GitHub Actions
        uses: ThiagoAnunciacao/s3cmd-sync-action@v0.2.4
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.s3_access_key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.s3_secret_key}}
          AWS_S3_BUCKET: ${{secrets.s3_bucket}}
          S3CMD_EXTRA_OPTS: --host=${{secrets.s3_host}} --host-bucket={{s3.host_bucket}} --acl-public
          S3CMD_SOURCE_DIR: rehydrate
          S3CMD_DELETE_REMOVED: false
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
